name: activation
services:
    activation-postgresql:
        image: postgres:18.4
        # volumes:
        #     - ~/volumes/jhipster/activation/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=activation
            - POSTGRES_PASSWORD=activation
            - POSTGRES_DB=activation
        healthcheck:
            test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
            interval: 5s
            timeout: 5s
            retries: 10
            # If you want to expose these ports outside your dev PC,
            # remove the "127.0.0.1:" prefix
        ports:
            - "127.0.0.1:${POSTGRES_PORT}:5432"
